//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Dados", "FK_BAIRRO_CIDADE", "CIDADE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dados.CIDADE), "BAIRRO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.BAIRRO), true)]
[assembly: EdmRelationshipAttribute("Dados", "FK_USUARIO_GRUPO", "GRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Dados.GRUPO), "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.USUARIO), true)]

#endregion

namespace Dados
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContextDB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContextDB object using the connection string found in the 'ContextDB' section of the application configuration file.
        /// </summary>
        public ContextDB() : base("name=ContextDB", "ContextDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContextDB object.
        /// </summary>
        public ContextDB(string connectionString) : base(connectionString, "ContextDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContextDB object.
        /// </summary>
        public ContextDB(EntityConnection connection) : base(connection, "ContextDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BAIRRO> BAIRRO
        {
            get
            {
                if ((_BAIRRO == null))
                {
                    _BAIRRO = base.CreateObjectSet<BAIRRO>("BAIRRO");
                }
                return _BAIRRO;
            }
        }
        private ObjectSet<BAIRRO> _BAIRRO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CIDADE> CIDADE
        {
            get
            {
                if ((_CIDADE == null))
                {
                    _CIDADE = base.CreateObjectSet<CIDADE>("CIDADE");
                }
                return _CIDADE;
            }
        }
        private ObjectSet<CIDADE> _CIDADE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GRUPO> GRUPO
        {
            get
            {
                if ((_GRUPO == null))
                {
                    _GRUPO = base.CreateObjectSet<GRUPO>("GRUPO");
                }
                return _GRUPO;
            }
        }
        private ObjectSet<GRUPO> _GRUPO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIO> USUARIO
        {
            get
            {
                if ((_USUARIO == null))
                {
                    _USUARIO = base.CreateObjectSet<USUARIO>("USUARIO");
                }
                return _USUARIO;
            }
        }
        private ObjectSet<USUARIO> _USUARIO;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BAIRRO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBAIRRO(BAIRRO bAIRRO)
        {
            base.AddObject("BAIRRO", bAIRRO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CIDADE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCIDADE(CIDADE cIDADE)
        {
            base.AddObject("CIDADE", cIDADE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GRUPO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGRUPO(GRUPO gRUPO)
        {
            base.AddObject("GRUPO", gRUPO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIO(USUARIO uSUARIO)
        {
            base.AddObject("USUARIO", uSUARIO);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dados", Name="BAIRRO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BAIRRO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BAIRRO object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iDCIDADE">Initial value of the IDCIDADE property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        public static BAIRRO CreateBAIRRO(global::System.Int32 id, global::System.Int32 iDCIDADE, global::System.String nOME)
        {
            BAIRRO bAIRRO = new BAIRRO();
            bAIRRO.ID = id;
            bAIRRO.IDCIDADE = iDCIDADE;
            bAIRRO.NOME = nOME;
            return bAIRRO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCIDADE
        {
            get
            {
                return _IDCIDADE;
            }
            set
            {
                OnIDCIDADEChanging(value);
                ReportPropertyChanging("IDCIDADE");
                _IDCIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCIDADE");
                OnIDCIDADEChanged();
            }
        }
        private global::System.Int32 _IDCIDADE;
        partial void OnIDCIDADEChanging(global::System.Int32 value);
        partial void OnIDCIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SIGLA
        {
            get
            {
                return _SIGLA;
            }
            set
            {
                OnSIGLAChanging(value);
                ReportPropertyChanging("SIGLA");
                _SIGLA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SIGLA");
                OnSIGLAChanged();
            }
        }
        private global::System.String _SIGLA;
        partial void OnSIGLAChanging(global::System.String value);
        partial void OnSIGLAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dados", "FK_BAIRRO_CIDADE", "CIDADE")]
        public CIDADE CIDADE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIDADE>("Dados.FK_BAIRRO_CIDADE", "CIDADE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIDADE>("Dados.FK_BAIRRO_CIDADE", "CIDADE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CIDADE> CIDADEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIDADE>("Dados.FK_BAIRRO_CIDADE", "CIDADE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CIDADE>("Dados.FK_BAIRRO_CIDADE", "CIDADE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dados", Name="CIDADE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CIDADE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CIDADE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="sIGLA">Initial value of the SIGLA property.</param>
        public static CIDADE CreateCIDADE(global::System.Int32 id, global::System.String nOME, global::System.String sIGLA)
        {
            CIDADE cIDADE = new CIDADE();
            cIDADE.ID = id;
            cIDADE.NOME = nOME;
            cIDADE.SIGLA = sIGLA;
            return cIDADE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIGLA
        {
            get
            {
                return _SIGLA;
            }
            set
            {
                OnSIGLAChanging(value);
                ReportPropertyChanging("SIGLA");
                _SIGLA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIGLA");
                OnSIGLAChanged();
            }
        }
        private global::System.String _SIGLA;
        partial void OnSIGLAChanging(global::System.String value);
        partial void OnSIGLAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dados", "FK_BAIRRO_CIDADE", "BAIRRO")]
        public EntityCollection<BAIRRO> BAIRRO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BAIRRO>("Dados.FK_BAIRRO_CIDADE", "BAIRRO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BAIRRO>("Dados.FK_BAIRRO_CIDADE", "BAIRRO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dados", Name="GRUPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GRUPO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GRUPO object.
        /// </summary>
        /// <param name="iDGRUPO">Initial value of the IDGRUPO property.</param>
        /// <param name="nOMEGRUPO">Initial value of the NOMEGRUPO property.</param>
        public static GRUPO CreateGRUPO(global::System.Int32 iDGRUPO, global::System.String nOMEGRUPO)
        {
            GRUPO gRUPO = new GRUPO();
            gRUPO.IDGRUPO = iDGRUPO;
            gRUPO.NOMEGRUPO = nOMEGRUPO;
            return gRUPO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDGRUPO
        {
            get
            {
                return _IDGRUPO;
            }
            set
            {
                if (_IDGRUPO != value)
                {
                    OnIDGRUPOChanging(value);
                    ReportPropertyChanging("IDGRUPO");
                    _IDGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDGRUPO");
                    OnIDGRUPOChanged();
                }
            }
        }
        private global::System.Int32 _IDGRUPO;
        partial void OnIDGRUPOChanging(global::System.Int32 value);
        partial void OnIDGRUPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEGRUPO
        {
            get
            {
                return _NOMEGRUPO;
            }
            set
            {
                OnNOMEGRUPOChanging(value);
                ReportPropertyChanging("NOMEGRUPO");
                _NOMEGRUPO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEGRUPO");
                OnNOMEGRUPOChanged();
            }
        }
        private global::System.String _NOMEGRUPO;
        partial void OnNOMEGRUPOChanging(global::System.String value);
        partial void OnNOMEGRUPOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dados", "FK_USUARIO_GRUPO", "USUARIO")]
        public EntityCollection<USUARIO> USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIO>("Dados.FK_USUARIO_GRUPO", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIO>("Dados.FK_USUARIO_GRUPO", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dados", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIO object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nOME">Initial value of the NOME property.</param>
        /// <param name="sOBRENOME">Initial value of the SOBRENOME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        /// <param name="dATANASCIMENTO">Initial value of the DATANASCIMENTO property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="sENHA">Initial value of the SENHA property.</param>
        /// <param name="lOGIN">Initial value of the LOGIN property.</param>
        public static USUARIO CreateUSUARIO(global::System.Int32 id, global::System.String nOME, global::System.String sOBRENOME, global::System.String eMAIL, global::System.DateTime dATANASCIMENTO, global::System.String cPF, global::System.String sENHA, global::System.String lOGIN)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.ID = id;
            uSUARIO.NOME = nOME;
            uSUARIO.SOBRENOME = sOBRENOME;
            uSUARIO.EMAIL = eMAIL;
            uSUARIO.DATANASCIMENTO = dATANASCIMENTO;
            uSUARIO.CPF = cPF;
            uSUARIO.SENHA = sENHA;
            uSUARIO.LOGIN = lOGIN;
            return uSUARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATANASCIMENTO
        {
            get
            {
                return _DATANASCIMENTO;
            }
            set
            {
                OnDATANASCIMENTOChanging(value);
                ReportPropertyChanging("DATANASCIMENTO");
                _DATANASCIMENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATANASCIMENTO");
                OnDATANASCIMENTOChanged();
            }
        }
        private global::System.DateTime _DATANASCIMENTO;
        partial void OnDATANASCIMENTOChanging(global::System.DateTime value);
        partial void OnDATANASCIMENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FOTO
        {
            get
            {
                return StructuralObject.GetValidValue(_FOTO);
            }
            set
            {
                OnFOTOChanging(value);
                ReportPropertyChanging("FOTO");
                _FOTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO");
                OnFOTOChanged();
            }
        }
        private global::System.Byte[] _FOTO;
        partial void OnFOTOChanging(global::System.Byte[] value);
        partial void OnFOTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SENHA
        {
            get
            {
                return _SENHA;
            }
            set
            {
                OnSENHAChanging(value);
                ReportPropertyChanging("SENHA");
                _SENHA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SENHA");
                OnSENHAChanged();
            }
        }
        private global::System.String _SENHA;
        partial void OnSENHAChanging(global::System.String value);
        partial void OnSENHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDGRUPO
        {
            get
            {
                return _IDGRUPO;
            }
            set
            {
                OnIDGRUPOChanging(value);
                ReportPropertyChanging("IDGRUPO");
                _IDGRUPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDGRUPO");
                OnIDGRUPOChanged();
            }
        }
        private Nullable<global::System.Int32> _IDGRUPO;
        partial void OnIDGRUPOChanging(Nullable<global::System.Int32> value);
        partial void OnIDGRUPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dados", "FK_USUARIO_GRUPO", "GRUPO")]
        public GRUPO GRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("Dados.FK_USUARIO_GRUPO", "GRUPO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("Dados.FK_USUARIO_GRUPO", "GRUPO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GRUPO> GRUPOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("Dados.FK_USUARIO_GRUPO", "GRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GRUPO>("Dados.FK_USUARIO_GRUPO", "GRUPO", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
