//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dados.FUNCIONALIDADE), "FUNCIONALIDADEGRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.FUNCIONALIDADEGRUPO), true)]
[assembly: EdmRelationshipAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dados.GRUPOS), "FUNCIONALIDADEGRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.FUNCIONALIDADEGRUPO), true)]
[assembly: EdmRelationshipAttribute("TesteMVCModel", "FK_USUARIOGRUPO_GRUPOS", "GRUPOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dados.GRUPOS), "USUARIOGRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.USUARIOGRUPO), true)]
[assembly: EdmRelationshipAttribute("TesteMVCModel", "FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dados.USUARIOUNIVERSUS), "USUARIOGRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dados.USUARIOGRUPO), true)]

#endregion

namespace Dados
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBContext object using the connection string found in the 'DBContext' section of the application configuration file.
        /// </summary>
        public DBContext() : base("name=DBContext", "DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBContext object.
        /// </summary>
        public DBContext(string connectionString) : base(connectionString, "DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBContext object.
        /// </summary>
        public DBContext(EntityConnection connection) : base(connection, "DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FUNCIONALIDADE> FUNCIONALIDADE
        {
            get
            {
                if ((_FUNCIONALIDADE == null))
                {
                    _FUNCIONALIDADE = base.CreateObjectSet<FUNCIONALIDADE>("FUNCIONALIDADE");
                }
                return _FUNCIONALIDADE;
            }
        }
        private ObjectSet<FUNCIONALIDADE> _FUNCIONALIDADE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FUNCIONALIDADEGRUPO> FUNCIONALIDADEGRUPO
        {
            get
            {
                if ((_FUNCIONALIDADEGRUPO == null))
                {
                    _FUNCIONALIDADEGRUPO = base.CreateObjectSet<FUNCIONALIDADEGRUPO>("FUNCIONALIDADEGRUPO");
                }
                return _FUNCIONALIDADEGRUPO;
            }
        }
        private ObjectSet<FUNCIONALIDADEGRUPO> _FUNCIONALIDADEGRUPO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GRUPOS> GRUPOS
        {
            get
            {
                if ((_GRUPOS == null))
                {
                    _GRUPOS = base.CreateObjectSet<GRUPOS>("GRUPOS");
                }
                return _GRUPOS;
            }
        }
        private ObjectSet<GRUPOS> _GRUPOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIOGRUPO> USUARIOGRUPO
        {
            get
            {
                if ((_USUARIOGRUPO == null))
                {
                    _USUARIOGRUPO = base.CreateObjectSet<USUARIOGRUPO>("USUARIOGRUPO");
                }
                return _USUARIOGRUPO;
            }
        }
        private ObjectSet<USUARIOGRUPO> _USUARIOGRUPO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIOUNIVERSUS> USUARIOUNIVERSUS
        {
            get
            {
                if ((_USUARIOUNIVERSUS == null))
                {
                    _USUARIOUNIVERSUS = base.CreateObjectSet<USUARIOUNIVERSUS>("USUARIOUNIVERSUS");
                }
                return _USUARIOUNIVERSUS;
            }
        }
        private ObjectSet<USUARIOUNIVERSUS> _USUARIOUNIVERSUS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FUNCIONALIDADE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFUNCIONALIDADE(FUNCIONALIDADE fUNCIONALIDADE)
        {
            base.AddObject("FUNCIONALIDADE", fUNCIONALIDADE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FUNCIONALIDADEGRUPO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFUNCIONALIDADEGRUPO(FUNCIONALIDADEGRUPO fUNCIONALIDADEGRUPO)
        {
            base.AddObject("FUNCIONALIDADEGRUPO", fUNCIONALIDADEGRUPO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GRUPOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGRUPOS(GRUPOS gRUPOS)
        {
            base.AddObject("GRUPOS", gRUPOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOGRUPO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOGRUPO(USUARIOGRUPO uSUARIOGRUPO)
        {
            base.AddObject("USUARIOGRUPO", uSUARIOGRUPO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOUNIVERSUS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOUNIVERSUS(USUARIOUNIVERSUS uSUARIOUNIVERSUS)
        {
            base.AddObject("USUARIOUNIVERSUS", uSUARIOUNIVERSUS);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TesteMVCModel", Name="FUNCIONALIDADE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FUNCIONALIDADE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FUNCIONALIDADE object.
        /// </summary>
        /// <param name="iDFUNCIONALIDADE">Initial value of the IDFUNCIONALIDADE property.</param>
        /// <param name="nOMEFUNCIONALIDADE">Initial value of the NOMEFUNCIONALIDADE property.</param>
        /// <param name="cODFUNCIONALIDADE">Initial value of the CODFUNCIONALIDADE property.</param>
        public static FUNCIONALIDADE CreateFUNCIONALIDADE(global::System.Int32 iDFUNCIONALIDADE, global::System.String nOMEFUNCIONALIDADE, global::System.String cODFUNCIONALIDADE)
        {
            FUNCIONALIDADE fUNCIONALIDADE = new FUNCIONALIDADE();
            fUNCIONALIDADE.IDFUNCIONALIDADE = iDFUNCIONALIDADE;
            fUNCIONALIDADE.NOMEFUNCIONALIDADE = nOMEFUNCIONALIDADE;
            fUNCIONALIDADE.CODFUNCIONALIDADE = cODFUNCIONALIDADE;
            return fUNCIONALIDADE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFUNCIONALIDADE
        {
            get
            {
                return _IDFUNCIONALIDADE;
            }
            set
            {
                if (_IDFUNCIONALIDADE != value)
                {
                    OnIDFUNCIONALIDADEChanging(value);
                    ReportPropertyChanging("IDFUNCIONALIDADE");
                    _IDFUNCIONALIDADE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFUNCIONALIDADE");
                    OnIDFUNCIONALIDADEChanged();
                }
            }
        }
        private global::System.Int32 _IDFUNCIONALIDADE;
        partial void OnIDFUNCIONALIDADEChanging(global::System.Int32 value);
        partial void OnIDFUNCIONALIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEFUNCIONALIDADE
        {
            get
            {
                return _NOMEFUNCIONALIDADE;
            }
            set
            {
                OnNOMEFUNCIONALIDADEChanging(value);
                ReportPropertyChanging("NOMEFUNCIONALIDADE");
                _NOMEFUNCIONALIDADE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEFUNCIONALIDADE");
                OnNOMEFUNCIONALIDADEChanged();
            }
        }
        private global::System.String _NOMEFUNCIONALIDADE;
        partial void OnNOMEFUNCIONALIDADEChanging(global::System.String value);
        partial void OnNOMEFUNCIONALIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODFUNCIONALIDADE
        {
            get
            {
                return _CODFUNCIONALIDADE;
            }
            set
            {
                OnCODFUNCIONALIDADEChanging(value);
                ReportPropertyChanging("CODFUNCIONALIDADE");
                _CODFUNCIONALIDADE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODFUNCIONALIDADE");
                OnCODFUNCIONALIDADEChanged();
            }
        }
        private global::System.String _CODFUNCIONALIDADE;
        partial void OnCODFUNCIONALIDADEChanging(global::System.String value);
        partial void OnCODFUNCIONALIDADEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADEGRUPO")]
        public EntityCollection<FUNCIONALIDADEGRUPO> FUNCIONALIDADEGRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FUNCIONALIDADEGRUPO>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADEGRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FUNCIONALIDADEGRUPO>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADEGRUPO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TesteMVCModel", Name="FUNCIONALIDADEGRUPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FUNCIONALIDADEGRUPO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FUNCIONALIDADEGRUPO object.
        /// </summary>
        /// <param name="iDFUNCIONALIDADEGRUPO">Initial value of the IDFUNCIONALIDADEGRUPO property.</param>
        /// <param name="iDFUNCIONALIDADE">Initial value of the IDFUNCIONALIDADE property.</param>
        /// <param name="iDGRUPO">Initial value of the IDGRUPO property.</param>
        public static FUNCIONALIDADEGRUPO CreateFUNCIONALIDADEGRUPO(global::System.Int32 iDFUNCIONALIDADEGRUPO, global::System.Int32 iDFUNCIONALIDADE, global::System.Int32 iDGRUPO)
        {
            FUNCIONALIDADEGRUPO fUNCIONALIDADEGRUPO = new FUNCIONALIDADEGRUPO();
            fUNCIONALIDADEGRUPO.IDFUNCIONALIDADEGRUPO = iDFUNCIONALIDADEGRUPO;
            fUNCIONALIDADEGRUPO.IDFUNCIONALIDADE = iDFUNCIONALIDADE;
            fUNCIONALIDADEGRUPO.IDGRUPO = iDGRUPO;
            return fUNCIONALIDADEGRUPO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFUNCIONALIDADEGRUPO
        {
            get
            {
                return _IDFUNCIONALIDADEGRUPO;
            }
            set
            {
                if (_IDFUNCIONALIDADEGRUPO != value)
                {
                    OnIDFUNCIONALIDADEGRUPOChanging(value);
                    ReportPropertyChanging("IDFUNCIONALIDADEGRUPO");
                    _IDFUNCIONALIDADEGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFUNCIONALIDADEGRUPO");
                    OnIDFUNCIONALIDADEGRUPOChanged();
                }
            }
        }
        private global::System.Int32 _IDFUNCIONALIDADEGRUPO;
        partial void OnIDFUNCIONALIDADEGRUPOChanging(global::System.Int32 value);
        partial void OnIDFUNCIONALIDADEGRUPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFUNCIONALIDADE
        {
            get
            {
                return _IDFUNCIONALIDADE;
            }
            set
            {
                OnIDFUNCIONALIDADEChanging(value);
                ReportPropertyChanging("IDFUNCIONALIDADE");
                _IDFUNCIONALIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFUNCIONALIDADE");
                OnIDFUNCIONALIDADEChanged();
            }
        }
        private global::System.Int32 _IDFUNCIONALIDADE;
        partial void OnIDFUNCIONALIDADEChanging(global::System.Int32 value);
        partial void OnIDFUNCIONALIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDGRUPO
        {
            get
            {
                return _IDGRUPO;
            }
            set
            {
                OnIDGRUPOChanging(value);
                ReportPropertyChanging("IDGRUPO");
                _IDGRUPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDGRUPO");
                OnIDGRUPOChanged();
            }
        }
        private global::System.Int32 _IDGRUPO;
        partial void OnIDGRUPOChanging(global::System.Int32 value);
        partial void OnIDGRUPOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE")]
        public FUNCIONALIDADE FUNCIONALIDADE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FUNCIONALIDADE>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FUNCIONALIDADE>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FUNCIONALIDADE> FUNCIONALIDADEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FUNCIONALIDADE>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FUNCIONALIDADE>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_FUNCIONALIDADE1", "FUNCIONALIDADE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS")]
        public GRUPOS GRUPOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GRUPOS> GRUPOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GRUPOS>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "GRUPOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TesteMVCModel", Name="GRUPOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GRUPOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GRUPOS object.
        /// </summary>
        /// <param name="iDGRUPO">Initial value of the IDGRUPO property.</param>
        public static GRUPOS CreateGRUPOS(global::System.Int32 iDGRUPO)
        {
            GRUPOS gRUPOS = new GRUPOS();
            gRUPOS.IDGRUPO = iDGRUPO;
            return gRUPOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDGRUPO
        {
            get
            {
                return _IDGRUPO;
            }
            set
            {
                if (_IDGRUPO != value)
                {
                    OnIDGRUPOChanging(value);
                    ReportPropertyChanging("IDGRUPO");
                    _IDGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDGRUPO");
                    OnIDGRUPOChanged();
                }
            }
        }
        private global::System.Int32 _IDGRUPO;
        partial void OnIDGRUPOChanging(global::System.Int32 value);
        partial void OnIDGRUPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMEGRUPO
        {
            get
            {
                return _NOMEGRUPO;
            }
            set
            {
                OnNOMEGRUPOChanging(value);
                ReportPropertyChanging("NOMEGRUPO");
                _NOMEGRUPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMEGRUPO");
                OnNOMEGRUPOChanged();
            }
        }
        private global::System.String _NOMEGRUPO;
        partial void OnNOMEGRUPOChanging(global::System.String value);
        partial void OnNOMEGRUPOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_FUNCIONALIDADEGRUPO_GRUPOS", "FUNCIONALIDADEGRUPO")]
        public EntityCollection<FUNCIONALIDADEGRUPO> FUNCIONALIDADEGRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FUNCIONALIDADEGRUPO>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "FUNCIONALIDADEGRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FUNCIONALIDADEGRUPO>("TesteMVCModel.FK_FUNCIONALIDADEGRUPO_GRUPOS", "FUNCIONALIDADEGRUPO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_USUARIOGRUPO_GRUPOS", "USUARIOGRUPO")]
        public EntityCollection<USUARIOGRUPO> USUARIOGRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOGRUPO>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "USUARIOGRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOGRUPO>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "USUARIOGRUPO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TesteMVCModel", Name="USUARIOGRUPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOGRUPO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIOGRUPO object.
        /// </summary>
        /// <param name="iDUSUARIOGRUPO">Initial value of the IDUSUARIOGRUPO property.</param>
        /// <param name="iDUSUARIOUNIVERSUS">Initial value of the IDUSUARIOUNIVERSUS property.</param>
        /// <param name="iDGRUPO">Initial value of the IDGRUPO property.</param>
        public static USUARIOGRUPO CreateUSUARIOGRUPO(global::System.Int32 iDUSUARIOGRUPO, global::System.Int32 iDUSUARIOUNIVERSUS, global::System.Int32 iDGRUPO)
        {
            USUARIOGRUPO uSUARIOGRUPO = new USUARIOGRUPO();
            uSUARIOGRUPO.IDUSUARIOGRUPO = iDUSUARIOGRUPO;
            uSUARIOGRUPO.IDUSUARIOUNIVERSUS = iDUSUARIOUNIVERSUS;
            uSUARIOGRUPO.IDGRUPO = iDGRUPO;
            return uSUARIOGRUPO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIOGRUPO
        {
            get
            {
                return _IDUSUARIOGRUPO;
            }
            set
            {
                if (_IDUSUARIOGRUPO != value)
                {
                    OnIDUSUARIOGRUPOChanging(value);
                    ReportPropertyChanging("IDUSUARIOGRUPO");
                    _IDUSUARIOGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIOGRUPO");
                    OnIDUSUARIOGRUPOChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIOGRUPO;
        partial void OnIDUSUARIOGRUPOChanging(global::System.Int32 value);
        partial void OnIDUSUARIOGRUPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIOUNIVERSUS
        {
            get
            {
                return _IDUSUARIOUNIVERSUS;
            }
            set
            {
                OnIDUSUARIOUNIVERSUSChanging(value);
                ReportPropertyChanging("IDUSUARIOUNIVERSUS");
                _IDUSUARIOUNIVERSUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUSUARIOUNIVERSUS");
                OnIDUSUARIOUNIVERSUSChanged();
            }
        }
        private global::System.Int32 _IDUSUARIOUNIVERSUS;
        partial void OnIDUSUARIOUNIVERSUSChanging(global::System.Int32 value);
        partial void OnIDUSUARIOUNIVERSUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDGRUPO
        {
            get
            {
                return _IDGRUPO;
            }
            set
            {
                OnIDGRUPOChanging(value);
                ReportPropertyChanging("IDGRUPO");
                _IDGRUPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDGRUPO");
                OnIDGRUPOChanged();
            }
        }
        private global::System.Int32 _IDGRUPO;
        partial void OnIDGRUPOChanging(global::System.Int32 value);
        partial void OnIDGRUPOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_USUARIOGRUPO_GRUPOS", "GRUPOS")]
        public GRUPOS GRUPOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "GRUPOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "GRUPOS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GRUPOS> GRUPOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPOS>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "GRUPOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GRUPOS>("TesteMVCModel.FK_USUARIOGRUPO_GRUPOS", "GRUPOS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS")]
        public USUARIOUNIVERSUS USUARIOUNIVERSUS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOUNIVERSUS>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOUNIVERSUS>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIOUNIVERSUS> USUARIOUNIVERSUSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIOUNIVERSUS>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIOUNIVERSUS>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOUNIVERSUS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TesteMVCModel", Name="USUARIOUNIVERSUS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOUNIVERSUS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIOUNIVERSUS object.
        /// </summary>
        /// <param name="iDUSUARIOUNIVERSUS">Initial value of the IDUSUARIOUNIVERSUS property.</param>
        public static USUARIOUNIVERSUS CreateUSUARIOUNIVERSUS(global::System.Int32 iDUSUARIOUNIVERSUS)
        {
            USUARIOUNIVERSUS uSUARIOUNIVERSUS = new USUARIOUNIVERSUS();
            uSUARIOUNIVERSUS.IDUSUARIOUNIVERSUS = iDUSUARIOUNIVERSUS;
            return uSUARIOUNIVERSUS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIOUNIVERSUS
        {
            get
            {
                return _IDUSUARIOUNIVERSUS;
            }
            set
            {
                if (_IDUSUARIOUNIVERSUS != value)
                {
                    OnIDUSUARIOUNIVERSUSChanging(value);
                    ReportPropertyChanging("IDUSUARIOUNIVERSUS");
                    _IDUSUARIOUNIVERSUS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIOUNIVERSUS");
                    OnIDUSUARIOUNIVERSUSChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIOUNIVERSUS;
        partial void OnIDUSUARIOUNIVERSUSChanging(global::System.Int32 value);
        partial void OnIDUSUARIOUNIVERSUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SINCRONIZARLMS
        {
            get
            {
                return _SINCRONIZARLMS;
            }
            set
            {
                OnSINCRONIZARLMSChanging(value);
                ReportPropertyChanging("SINCRONIZARLMS");
                _SINCRONIZARLMS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SINCRONIZARLMS");
                OnSINCRONIZARLMSChanged();
            }
        }
        private Nullable<global::System.Boolean> _SINCRONIZARLMS;
        partial void OnSINCRONIZARLMSChanging(Nullable<global::System.Boolean> value);
        partial void OnSINCRONIZARLMSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SENHAPADRAO
        {
            get
            {
                return _SENHAPADRAO;
            }
            set
            {
                OnSENHAPADRAOChanging(value);
                ReportPropertyChanging("SENHAPADRAO");
                _SENHAPADRAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SENHAPADRAO");
                OnSENHAPADRAOChanged();
            }
        }
        private global::System.String _SENHAPADRAO;
        partial void OnSENHAPADRAOChanging(global::System.String value);
        partial void OnSENHAPADRAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CODPESSOA
        {
            get
            {
                return _CODPESSOA;
            }
            set
            {
                OnCODPESSOAChanging(value);
                ReportPropertyChanging("CODPESSOA");
                _CODPESSOA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CODPESSOA");
                OnCODPESSOAChanged();
            }
        }
        private Nullable<global::System.Int32> _CODPESSOA;
        partial void OnCODPESSOAChanging(Nullable<global::System.Int32> value);
        partial void OnCODPESSOAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ATIVO
        {
            get
            {
                return _ATIVO;
            }
            set
            {
                OnATIVOChanging(value);
                ReportPropertyChanging("ATIVO");
                _ATIVO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ATIVO");
                OnATIVOChanged();
            }
        }
        private Nullable<global::System.Boolean> _ATIVO;
        partial void OnATIVOChanging(Nullable<global::System.Boolean> value);
        partial void OnATIVOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DTCRIACAO
        {
            get
            {
                return _DTCRIACAO;
            }
            set
            {
                OnDTCRIACAOChanging(value);
                ReportPropertyChanging("DTCRIACAO");
                _DTCRIACAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DTCRIACAO");
                OnDTCRIACAOChanged();
            }
        }
        private Nullable<global::System.DateTime> _DTCRIACAO;
        partial void OnDTCRIACAOChanging(Nullable<global::System.DateTime> value);
        partial void OnDTCRIACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DTMODIFICACAO
        {
            get
            {
                return _DTMODIFICACAO;
            }
            set
            {
                OnDTMODIFICACAOChanging(value);
                ReportPropertyChanging("DTMODIFICACAO");
                _DTMODIFICACAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DTMODIFICACAO");
                OnDTMODIFICACAOChanged();
            }
        }
        private Nullable<global::System.DateTime> _DTMODIFICACAO;
        partial void OnDTMODIFICACAOChanging(Nullable<global::System.DateTime> value);
        partial void OnDTMODIFICACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DTEXPORTACAO
        {
            get
            {
                return _DTEXPORTACAO;
            }
            set
            {
                OnDTEXPORTACAOChanging(value);
                ReportPropertyChanging("DTEXPORTACAO");
                _DTEXPORTACAO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DTEXPORTACAO");
                OnDTEXPORTACAOChanged();
            }
        }
        private Nullable<global::System.DateTime> _DTEXPORTACAO;
        partial void OnDTEXPORTACAOChanging(Nullable<global::System.DateTime> value);
        partial void OnDTEXPORTACAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] VERSAOREPOSITORIO
        {
            get
            {
                return StructuralObject.GetValidValue(_VERSAOREPOSITORIO);
            }
            set
            {
                OnVERSAOREPOSITORIOChanging(value);
                ReportPropertyChanging("VERSAOREPOSITORIO");
                _VERSAOREPOSITORIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSAOREPOSITORIO");
                OnVERSAOREPOSITORIOChanged();
            }
        }
        private global::System.Byte[] _VERSAOREPOSITORIO;
        partial void OnVERSAOREPOSITORIOChanging(global::System.Byte[] value);
        partial void OnVERSAOREPOSITORIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SINCRONIZADOCOMFALHA
        {
            get
            {
                return _SINCRONIZADOCOMFALHA;
            }
            set
            {
                OnSINCRONIZADOCOMFALHAChanging(value);
                ReportPropertyChanging("SINCRONIZADOCOMFALHA");
                _SINCRONIZADOCOMFALHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SINCRONIZADOCOMFALHA");
                OnSINCRONIZADOCOMFALHAChanged();
            }
        }
        private Nullable<global::System.Boolean> _SINCRONIZADOCOMFALHA;
        partial void OnSINCRONIZADOCOMFALHAChanging(Nullable<global::System.Boolean> value);
        partial void OnSINCRONIZADOCOMFALHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FOTO
        {
            get
            {
                return StructuralObject.GetValidValue(_FOTO);
            }
            set
            {
                OnFOTOChanging(value);
                ReportPropertyChanging("FOTO");
                _FOTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FOTO");
                OnFOTOChanged();
            }
        }
        private global::System.Byte[] _FOTO;
        partial void OnFOTOChanging(global::System.Byte[] value);
        partial void OnFOTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> USUARIOADMINISTRATIVO
        {
            get
            {
                return _USUARIOADMINISTRATIVO;
            }
            set
            {
                OnUSUARIOADMINISTRATIVOChanging(value);
                ReportPropertyChanging("USUARIOADMINISTRATIVO");
                _USUARIOADMINISTRATIVO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USUARIOADMINISTRATIVO");
                OnUSUARIOADMINISTRATIVOChanged();
            }
        }
        private Nullable<global::System.Boolean> _USUARIOADMINISTRATIVO;
        partial void OnUSUARIOADMINISTRATIVOChanging(Nullable<global::System.Boolean> value);
        partial void OnUSUARIOADMINISTRATIVOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] VERSAOREPOSITORIOFOTO
        {
            get
            {
                return StructuralObject.GetValidValue(_VERSAOREPOSITORIOFOTO);
            }
            set
            {
                OnVERSAOREPOSITORIOFOTOChanging(value);
                ReportPropertyChanging("VERSAOREPOSITORIOFOTO");
                _VERSAOREPOSITORIOFOTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSAOREPOSITORIOFOTO");
                OnVERSAOREPOSITORIOFOTOChanged();
            }
        }
        private global::System.Byte[] _VERSAOREPOSITORIOFOTO;
        partial void OnVERSAOREPOSITORIOFOTOChanging(global::System.Byte[] value);
        partial void OnVERSAOREPOSITORIOFOTOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TesteMVCModel", "FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOGRUPO")]
        public EntityCollection<USUARIOGRUPO> USUARIOGRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOGRUPO>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOGRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOGRUPO>("TesteMVCModel.FK_USUARIOGRUPO_USUARIOUNIVERSUS", "USUARIOGRUPO", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
